### PR TITLE
check if a request id exists

### LINKED ISSUE #94: OPTIONS request using CORS plugin throws "DOMException"
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

3.3.0

### Node.js version

16.17.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6.1

### Description

Currently having an issue with this plugin were it is throwing an exception on an OPTIONS request.

When sending an OPTIONS request i get the following error:
```
[1671197987834] INFO (80457 on Danes-MBP-2.lan): incoming request
    reqId: "req-1"
    req: {
      "method": "OPTIONS",
      "url": "/",
      "hostname": "localhost:8080",
      "remoteAddress": "127.0.0.1",
      "remotePort": 64770
    }
[1671197987835] INFO (80457 on Danes-MBP-2.lan): The "on-request-undefined" performance mark has not been set
    reqId: "req-1"
    res: {
      "statusCode": 400
    }
    err: {
      "type": "DOMException",
      "message": "The \"on-request-undefined\" performance mark has not been set",
      "stack":
          SyntaxError: The "on-request-undefined" performance mark has not been set
              at new DOMException (node:internal/per_context/domexception:72:5)
              at __node_internal_ (node:internal/util:497:10)
              at getMark (node:internal/perf/usertiming:58:11)
              at calculateStartDuration (node:internal/perf/usertiming:141:13)
              at EventTarget.measure (node:internal/perf/usertiming:159:7)
              at Object.<anonymous> (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/@fastify/routes-stats/index.js:51:17)
              at next (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/fastify/lib/hooks.js:219:30)
              at onSendHookRunner (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/fastify/lib/hooks.js:241:3)
              at onSendHook (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/fastify/lib/reply.js:521:5)
              at Reply.send (/Users/danewilson/Development/scratchpad/fastify-test/node_modules/fastify/lib/reply.js:196:3)
      "name": "SyntaxError",
      "code": 12,
      "INDEX_SIZE_ERR": 1,
      "DOMSTRING_SIZE_ERR": 2,
      "HIERARCHY_REQUEST_ERR": 3,
      "WRONG_DOCUMENT_ERR": 4,
      "INVALID_CHARACTER_ERR": 5,
      "NO_DATA_ALLOWED_ERR": 6,
      "NO_MODIFICATION_ALLOWED_ERR": 7,
      "NOT_FOUND_ERR": 8,
      "NOT_SUPPORTED_ERR": 9,
      "INUSE_ATTRIBUTE_ERR": 10,
      "INVALID_STATE_ERR": 11,
      "SYNTAX_ERR": 12,
      "INVALID_MODIFICATION_ERR": 13,
      "NAMESPACE_ERR": 14,
      "INVALID_ACCESS_ERR": 15,
      "VALIDATION_ERR": 16,
      "TYPE_MISMATCH_ERR": 17,
      "SECURITY_ERR": 18,
      "NETWORK_ERR": 19,
      "ABORT_ERR": 20,
      "URL_MISMATCH_ERR": 21,
      "QUOTA_EXCEEDED_ERR": 22,
      "TIMEOUT_ERR": 23,
      "INVALID_NODE_TYPE_ERR": 24,
      "DATA_CLONE_ERR": 25
    }
[1671197987838] INFO (80457 on Danes-MBP-2.lan): request completed
    reqId: "req-1"
    res: {
      "statusCode": 400
    }
    responseTime: 3.5796658992767334
``` 

### Steps to Reproduce

```js
// app.js

const routeStats = require("@fastify/routes-stats");
const fastifyCors = require("@fastify/cors");

module.exports = async function (fastify, opts) {
  fastify.register(fastifyCors);
  fastify.register(routeStats);

  fastify.post(
    "/test",
    function () {
      return {
        message: "Success.",
      };
    }
  );
}
```
Run `fastify start -p 8080 -l info -P app.js`
Then run `curl -X OPTIONS http://localhost:8080/`

### Expected Behavior

For the request to resolve correctly and measure the routes stats.

### PR DESCRIPTION
**Pull request by cberescu**
Fixes #94 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Regarding  https://github.com/fastify/fastify-routes-stats/issues/94 , it checks if an request id exists before setting the onSend mark and making the measurements.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -64,8 +64,11 @@ async function fastifyRoutesStats (fastify, opts) {
     performance.mark(ONSEND + id)
 
     const key = `${ROUTES}${request.raw.method}|${routeId}`
-    performance.measure(key, ONREQUEST + id, ONSEND + id)
-
+    try {
```
Comment (Uzlopak) [inline index.js:67]: Cant we avoid the try catch?

Comment (Uzlopak) [reply index.js:67]: You should find the id not in the raw object but directly on request.
See
https://github.com/fastify/fastify/blob/4c416774ae20c5ea80a5301f0485877512a36da1/lib/request.js#L29

Comment (cberescu) [reply index.js:67]: also, can we do something like (adding the reply.mark param): 
``` 
 fastify.addHook('onRequest', function (request, reply, next) {
    const id = request.id
    performance.mark(ONREQUEST + id)
    reply.mark = true;
    next()
  })
```

And check the `mark` param in the `onSend` ? This way we don't need the try..catch,.. part

Comment (cberescu) [reply index.js:67]: @Uzlopak any feedback on the proposal ?

Comment (Uzlopak) [reply index.js:67]: I would rather analyze why the id was used in the first place. When using request.id then the unit tests fail. So something is odd.

Comment (cberescu) [reply index.js]: they don't seem to fail when i checked...

File: index.js [hunk 2]
```diff
@@ -50,8 +50,9 @@ async function fastifyRoutesStats (fastify, opts) {
   obs.observe({ entryTypes: ['measure'], buffered: true })
 
   fastify.addHook('onRequest', function (request, reply, next) {
-    const id = request.raw.id
+    const id = request.id
     performance.mark(ONREQUEST + id)
+    reply.context.performanceMark = true;
```
Comment (climba03003) [inline index.js:55]: Do not modify the internal object.
`context` do not means to be used by `plugin` except `context.config`.

**Review by climba03003 — CHANGES_REQUESTED** [review]

**Review by mcollina — COMMENTED** [review]
I think we should be calling the property `performanceMarked` as it was marked.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — APPROVED** [review]

File: index.js [hunk 3]
```diff
@@ -48,10 +49,12 @@ async function fastifyRoutesStats (fastify, opts) {
...
 
   obs.observe({ entryTypes: ['measure'], buffered: true })
+  fastify.decorateRequest(decoratorName, false)
 
   fastify.addHook('onRequest', function (request, reply, next) {
-    const id = request.raw.id
+    const id = request.id
     performance.mark(ONREQUEST + id)
+    request[decoratorName] = true
     next()
```
Comment (Uzlopak) [inline index.js:58]:
```suggestion
    performance.mark(ONREQUEST + request.id)
    request[decoratorName] = true
    next()
```

File: index.js [hunk 4]
```diff
@@ -60,14 +63,15 @@ async function fastifyRoutesStats (fastify, opts) {
       ? reply.context.config.statsId
       : request.raw.url
 
-    const id = request.raw.id
```
Comment (Uzlopak) [inline index.js:63]:
```js
  fastify.addHook('onSend', function (request, reply, _, next) {
    if (request[decoratorName]) {
      const routeId = reply.context.config.statsId
        ? reply.context.config.statsId
        : request.raw.url

      const id = request.id
      const key = `${ROUTES}${request.raw.method}|${routeId}`

      performance.mark(ONSEND + id)
      performance.measure(key, ONREQUEST + id, ONSEND + id)
      performance.clearMarks(ONSEND + id)
      performance.clearMarks(ONREQUEST + id)
    } else {
      fastify.log.error('missing request mark')
    }

    next()
  })
```

Comment (Uzlopak) [reply index.js:63]: we dont need all the variables if the request is missing the decorated attribute.

Comment (Uzlopak) [reply index.js:63]: Actually... why do I even used a ternary operation?!
the folowing should be equivalent

`const routeId = reply.context.config.statsId || request.raw.url`

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by Uzlopak** [comment]
Thanks for the great work.

**Comment by Uzlopak** [comment]
@mcollina 

Time for a release :)
